Fix Garbage Collection error
Fixes an error which could occur on red 3.5 where the Garbage collector was trying to delete something which was already removed:

[CRITICAL] red.main: Caught unhandled exception in <Task finished name='Task-203935' coro=<Adventure._garbage_collection() done, defined at adventure.py:474> exception=TypeError('cannot unpack non-iterable int object')>:
Task exception was never retrieved
Traceback (most recent call last):
  File "./cogs/CogManager/cogs/adventure/adventure.py", line 479, in _garbage_collection
    async for guild_id, session in AsyncIter(self._sessions.copy(), steps=100):
TypeError: cannot unpack non-iterable int object